Update index.md
posva/unplugin-vue-router pull request #324
Opened 2024-02-22 16:34 UTC by padcom

A few upper/lower case changes, probably stemming from previous versions of the document.

2024-02-22 16:46 UTC, posva requested changes
Thanks a lot! let's keep Data Loaders with both uppercase

2024-02-22 16:46 UTC, posva commented on docs/rfcs/data-loaders/index.md
> +Using `Suspense` is probably the first alternative that comes to mind and it has been considered as a solution for data fetching by implementing proofs of concepts. It however suffers from major draw
```suggestion
Using Suspense is probably the first alternative that comes to mind and it has been considered as a solution for data fetching by implementing proofs of concepts. It however suffers from major drawbacks that are tied to its current design and is not a viable solution for data fetching.
```

2024-02-22 16:49 UTC, padcom commented
> Thanks a lot! let's keep Data Loaders with both uppercase

Sure - how about consistency? At the beginning of the document, those are mostly Upper Case, then the closer to the end they are all lower case. Are you saying you want to keep them throughout the document as Data Loaders, both uppercased?

2024-02-22 19:13 UTC, posva commented
Not necessarily. Let’s just revert the one that were changed. I will deal with consistency later on

2024-02-22 20:26 UTC, padcom commented
Done.

2024-02-23 07:52 UTC, posva approved these changes
Thanks a lot!

2024-02-23 07:52 UTC, merged